SHOW DATABASES;

USE HACKERRANK;

SHOW TABLES;

CREATE TABLE CHALLENGES_HACKERS (
    HACKER_ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CHALLENGES_CHALLENGES (
    CHALLENGE_ID INT NOT NULL,
    HACKER_ID INT NOT NULL
);

INSERT INTO CHALLENGES_HACKERS VALUES (5077,'Rose');
INSERT INTO CHALLENGES_HACKERS VALUES (21283,'Angela');
INSERT INTO CHALLENGES_HACKERS VALUES (62743,'Frank');
INSERT INTO CHALLENGES_HACKERS VALUES (88255,'Patrick');
INSERT INTO CHALLENGES_HACKERS VALUES (96196,'Lisa');

INSERT INTO CHALLENGES_CHALLENGES VALUES (61654,5077);
INSERT INTO CHALLENGES_CHALLENGES VALUES (58302,21283);
INSERT INTO CHALLENGES_CHALLENGES VALUES (40587,88255);
INSERT INTO CHALLENGES_CHALLENGES VALUES (29477,5077);
INSERT INTO CHALLENGES_CHALLENGES VALUES (1220,21283);
INSERT INTO CHALLENGES_CHALLENGES VALUES (69514,21283);
INSERT INTO CHALLENGES_CHALLENGES VALUES (46561,62743);
INSERT INTO CHALLENGES_CHALLENGES VALUES (58077,62743);
INSERT INTO CHALLENGES_CHALLENGES VALUES (18483,88255);
INSERT INTO CHALLENGES_CHALLENGES VALUES (76766,21283);
INSERT INTO CHALLENGES_CHALLENGES VALUES (52382,5077);
INSERT INTO CHALLENGES_CHALLENGES VALUES (74467,21283);
INSERT INTO CHALLENGES_CHALLENGES VALUES (33625,96196);
INSERT INTO CHALLENGES_CHALLENGES VALUES (26053,88255);
INSERT INTO CHALLENGES_CHALLENGES VALUES (42665,62743);
INSERT INTO CHALLENGES_CHALLENGES VALUES (12859,62743);
INSERT INTO CHALLENGES_CHALLENGES VALUES (70094,21283);
INSERT INTO CHALLENGES_CHALLENGES VALUES (34599,88255);
INSERT INTO CHALLENGES_CHALLENGES VALUES (54680,88255);
INSERT INTO CHALLENGES_CHALLENGES VALUES (61881,5077);


-- BETTER SOLUTION
SELECT H.HACKER_ID,H.NAME,
       COUNT(C.CHALLENGE_ID) AS TOTAL
FROM CHALLENGES_HACKERS AS H
    INNER JOIN CHALLENGES_CHALLENGES C
        ON H.HACKER_ID = C.HACKER_ID
    GROUP BY H.HACKER_ID,H.NAME
    HAVING
            TOTAL =
            (
              SELECT MAX(T1.HACKER_T1)
              FROM (
                    SELECT COUNT(HACKER_ID) AS HACKER_T1
                    FROM CHALLENGES_CHALLENGES
                    GROUP BY HACKER_ID
                   )AS T1
            )

            OR

            TOTAL IN
            (
              SELECT T2.HACKER_T2
              FROM
                    (
                     SELECT COUNT(*) AS HACKER_T2
                     FROM CHALLENGES_CHALLENGES
                     GROUP BY HACKER_ID
                     ) AS T2
              GROUP BY T2.HACKER_T2
              HAVING COUNT(*) = 1
            )

ORDER BY TOTAL DESC,H.HACKER_ID
